### ISSUE TITLE
Issue when running haml-lint, updated to v. 0.15.2

### ISSUE THREAD

**Issue by justinelam** [brigade/haml-lint#104] opened 2016-01-07 17:14 UTC
```
$haml-lint app/views/organizations/
undefined method `-' for nil:NilClass
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/linter/space_before_script.rb:29:in `visit_tag'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:38:in `safe_send'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:17:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `block in visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `each'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:28:in `visit_children'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/haml_visitor.rb:22:in `visit'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/linter.rb:28:in `run'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/runner.rb:58:in `block in collect_lints'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/runner.rb:57:in `map'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/runner.rb:57:in `collect_lints'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/runner.rb:21:in `block in run'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/runner.rb:20:in `map'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/runner.rb:20:in `run'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/cli.rb:82:in `scan_for_lints'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/cli.rb:51:in `act_on_options'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/lib/haml_lint/cli.rb:23:in `run'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/gems/haml_lint-0.15.2/bin/haml-lint:7:in `<top (required)>'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/bin/haml-lint:23:in `load'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/bin/haml-lint:23:in `<main>'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `eval'
/Users/justinelam/.rvm/gems/ruby-2.0.0-p576/bin/ruby_executable_hooks:15:in `<main>'
Report this bug at https://github.com/brigade/haml-lint/issues

To help fix this issue, please include:
- The above stack trace
- Haml-Lint version: 0.15.2
- Haml version: 4.0.6
- RuboCop version: 0.35.1
- Ruby version: 2.0.0
```

**Comment by sds** [comment] 2016-01-19 00:24
Hey @justinelam, thanks for the bug report.

Could you include a snippet of HAML code that reproduces this issue? It would help tremendously in fixing the issue. Thanks!

**Comment by oliverklee** [comment] 2016-02-04 13:14
@justinelam We had the same issue (or at least the same error message). It turned out that we were still using the outdated haml-lint gem (which goes only up to version 0.13.0) instead  of the new haml_lint gem (which starts at 0.13.0 and goes up to the latest 0.16.0). You might want to check that you are using the haml_lint gem and not the haml-lint gem anymore.

**Comment by sds** [comment] 2016-02-10 15:57
Thanks for sharing your discovery, @oliverklee.

Closing due to lack of movement on this issue. Feel free to reopen if you can provide a reproducible case. Thanks!

**Closed by sds** 2016-02-10 15:57 UTC
Labels: bug
