### ISSUE TITLE
cannot load such file -- astrolabe/builder (LoadError)

### ISSUE THREAD

**Issue by lucascaton** [brigade/haml-lint#108] opened 2016-01-18 23:54 UTC
When using Rubocop `0.36.0`, I get the following error:

```ruby
haml-lint-0.13.0/lib/haml_lint/ruby_parser.rb:1:in `require': cannot load such file -- astrolabe/builder (LoadError)
```

**Comment by lucascaton** [comment] 2016-01-18 23:55
Just realised that https://github.com/brigade/haml-lint/pull/106 will fix it.

**Comment by sds** [comment] 2016-01-19 00:00
Fixed by 5bf550f923f0bfb6f73fe77bd1a1bfa0f4f0ebf5. Thanks!

**Closed by sds** 2016-01-19 00:00 UTC
Labels: bug

**Comment by lucascaton** [comment] 2016-01-19 00:03
Thanks @sds, are you going to bump the version? Cheers!

**Comment by sds** [comment] 2016-01-19 01:45
I'm waiting to hear back on #104 since a couple of people have reported it but none have provided a code snippet to help reproduce. If I hear nothing in a few days I'll cut a new release (but would really like to fix that bug first).

If you want to use haml-lint before then, you can always update your `Gemfile` to use the GitHub master branch.

**Comment by lucascaton** [comment] 2016-01-19 01:54
@sds sure!

`gem 'haml_lint', require: false, github: 'brigade/haml-lint'` fixed my problem, thanks! :smile:
