### ISSUE TITLE
Rubocop: unexpected token $end

### ISSUE THREAD

**Issue by dylangrafmyre** [brigade/haml-lint#91] opened 2015-08-18 02:49 UTC
Hello, 

I am having no luck finding out what in this haml code is causing this issue. Hoping someone would have a suggestion or is this a parser issue?

```haml
- cache(cache_key_for_location_calendar(location, start_date, days_to_display)) do
  - calendar_time_slots = get_calendar_time_slots_for_week(location, start_date, current_user.id,
                                                           days_to_display)
  %table.table.table-bordered.reservation-table#reservation-table{ border: "0", cellpadding: "0",
    cellspacing: "0", "table-layout" => "fixed", data: { "row-count" => calendar_time_slots[0].size,
                                                         "location-id" => location_id,
                                                         "first-appt-time" => calendar_time_slots[0].keys.first } }
    %tr
      %td.time-col
        - calendar_time_slots[0].each_key do |key| # use the first hash, but all should have the same keys
          .time-col
            - key = "Noon" if key == "12:00pm"
            = key
      - days_to_display.to_i.times do |i|
        - date = start_date + i.days
        %td.reservation-col{ class: "day day_#{i + 1}", data: { day: "#{date.strftime(Format::DATE_TRANSFER)}" } }
          - calendar_time_slots[i].each do |key, cal_info|
            - clas = cal_info.to_s
            .reservation-col{ class: clas, data: { status: cal_info.to_s } }
              - if cal_info == :available
                %span
                  = cal_info.to_s.capitalize
              - else
                Unavailable
```

Thanks!
Dylan

**Comment by sds** [comment] 2015-08-19 05:47
Thanks for the report, @dylangrafmyre!

Fixed by 32cd092e090ad5e120ff1ab17a41b18b1041ae0c. 

This was caused by the trailing comment on the following line:

```haml
- calendar_time_slots[0].each_key do |key| # use the first hash, but all should have the same keys
```

...so to fix your problem until the next release of `haml-lint` you can just move that comment onto a separate line. Hope that helps!

**Closed by sds** 2015-08-19 05:47 UTC
Labels: bug
