### ISSUE TITLE
Bug with output comment `=# ...`

### ISSUE THREAD

**Issue by KODerFunk** [brigade/haml-lint#83] opened 2015-06-24 07:53 UTC
Partial like this:
```haml
.b-links
  = link_to_current "some link", some_route_path, class: "b-links__link"
  =# link_to_current "some todo link, "TODO", class: "b-links__link"
```
cause this:
```
myuser:myproject myuser$ bundle exec haml-lint app/views/some_dir/_links.html.haml 
undefined method `type' for nil:NilClass
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/linter/unnecessary_string_output.rb:34:in `outputs_string_literal?'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/linter/unnecessary_string_output.rb:25:in `visit_script'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:18:in `visit'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `block in visit_children'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `each'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:27:in `visit_children'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/haml_visitor.rb:23:in `visit'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/linter.rb:17:in `run'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:63:in `block in find_lints'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:62:in `each'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:62:in `find_lints'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:22:in `block in run'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:21:in `each'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/runner.rb:21:in `run'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/cli.rb:73:in `scan_for_lints'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/cli.rb:47:in `act_on_options'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/lib/haml_lint/cli.rb:22:in `run'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/gems/haml-lint-0.13.0/bin/haml-lint:7:in `<top (required)>'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/bin/haml-lint:23:in `load'
/Users/myuser/.rvm/gems/ruby-2.2.2@myproject/bin/haml-lint:23:in `<main>'
Report this bug at https://github.com/brigade/haml-lint/issues
```

**Comment by sds** [comment] 2015-06-24 15:56
Duplicate of #82. Thanks for the report!

**Closed by sds** 2015-06-24 15:56 UTC
Labels: duplicate
