### ISSUE TITLE
undefined method `call' for HamlLint::Tree::NullNode:Class

### ISSUE THREAD

**Issue by tonydefaria** [brigade/haml-lint#190] opened 2017-03-09 11:24 UTC
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/tree/root_node.rb:18:in `find'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/tree/root_node.rb:18:in `node_for_line'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/linter/final_newline.rb:9:in `visit_root'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/haml_visitor.rb:40:in `safe_send'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/haml_visitor.rb:19:in `visit'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/linter.rb:28:in `run'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/runner.rb:84:in `block in collect_lints'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/runner.rb:83:in `map'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/runner.rb:83:in `collect_lints'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/runner.rb:119:in `process_file'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/runner.rb:108:in `block in process_files'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/runner.rb:107:in `each'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/runner.rb:107:in `process_files'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/runner.rb:132:in `report'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/runner.rb:23:in `run'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/cli.rb:92:in `scan_for_lints'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/cli.rb:51:in `act_on_options'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/lib/haml_lint/cli.rb:23:in `run'
/Users/tonydefaria/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/haml_lint-0.22.1/bin/haml-lint:7:in `<top (required)>'
/Users/tonydefaria/.rbenv/versions/2.4.0/bin/haml-lint:22:in `load'
/Users/tonydefaria/.rbenv/versions/2.4.0/bin/haml-lint:22:in `<main>'
- Haml-Lint version: 0.22.1
- Haml version: 4.0.7
- RuboCop version: 0.47.1
- Ruby version: 2.4.0

**Comment by michaelherold** [comment] 2017-03-09 12:23
This is a duplicate of #186.

**Comment by tonydefaria** [comment] 2017-03-09 13:20
@michaelherold you are correct. Sorry for the duplication and thanks for the feedback. Have a good one ;)

**Comment by trotzig** [comment] 2017-03-09 13:52
Fixed in 405a153

**Closed by trotzig** 2017-03-09 13:52 UTC
